import { FavoriteFlash } from "./favorites";

export interface ExportOptions {
  flashes: FavoriteFlash[];
  title?: string;
  gridSize?: number;
  imageSize?: number;
  backgroundColor?: string;
  textColor?: string;
}

export async function exportAsImageGrid({
  flashes,
  title = "FLASHCASTR COLLECTION",
  gridSize = 4,
  imageSize = 200,
  backgroundColor = "#000000",
  textColor = "#00ff00"
}: ExportOptions): Promise<void> {
  if (flashes.length === 0) return;

  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const padding = 20;
  const headerHeight = 80;
  const footerHeight = 60;
  const gap = 10;
  
  const rows = Math.ceil(flashes.length / gridSize);
  const actualCols = Math.min(flashes.length, gridSize);
  
  canvas.width = (actualCols * imageSize) + ((actualCols - 1) * gap) + (padding * 2);
  canvas.height = (rows * imageSize) + ((rows - 1) * gap) + headerHeight + footerHeight + (padding * 2);

  // Background
  ctx.fillStyle = backgroundColor;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Header
  ctx.fillStyle = textColor;
  ctx.font = 'bold 20px monospace';
  ctx.textAlign = 'center';
  ctx.fillText(title, canvas.width / 2, 40);
  
  ctx.font = '12px monospace';
  ctx.fillText(`${flashes.length} SAVED FLASHES • ${new Date().toLocaleDateString()}`, canvas.width / 2, 60);

  // Load and draw images
  const imagePromises = flashes.slice(0, gridSize * rows).map(async (flash, index) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    
    return new Promise<void>((resolve) => {
      img.onload = () => {
        const row = Math.floor(index / gridSize);
        const col = index % gridSize;
        
        const x = padding + (col * (imageSize + gap));
        const y = padding + headerHeight + (row * (imageSize + gap));
        
        // Draw image
        ctx.drawImage(img, x, y, imageSize, imageSize);
        
        // Draw overlay info
        ctx.fillStyle = 'rgba(0, 0, 0, 0.7)';
        ctx.fillRect(x, y + imageSize - 40, imageSize, 40);
        
        ctx.fillStyle = textColor;
        ctx.font = '10px monospace';
        ctx.textAlign = 'left';
        ctx.fillText(`#${flash.flash_id}`, x + 5, y + imageSize - 25);
        ctx.fillText(`@${flash.player}`, x + 5, y + imageSize - 15);
        ctx.fillText(`${flash.city}`, x + 5, y + imageSize - 5);
        
        resolve();
      };
      
      img.onerror = () => {
        // Draw placeholder if image fails to load
        ctx.fillStyle = '#333333';
        const row = Math.floor(index / gridSize);
        const col = index % gridSize;
        const x = padding + (col * (imageSize + gap));
        const y = padding + headerHeight + (row * (imageSize + gap));
        ctx.fillRect(x, y, imageSize, imageSize);
        
        ctx.fillStyle = textColor;
        ctx.font = '12px monospace';
        ctx.textAlign = 'center';
        ctx.fillText('IMAGE', x + imageSize/2, y + imageSize/2 - 10);
        ctx.fillText('NOT FOUND', x + imageSize/2, y + imageSize/2 + 10);
        
        resolve();
      };
      
      // Try to get image URL
      const imageUrl = flash.ipfs_cid 
        ? `https://fuchsia-rich-lungfish-648.mypinata.cloud/ipfs/${flash.ipfs_cid}`
        : flash.img || '';
        
      img.src = imageUrl;
    });
  });

  try {
    await Promise.all(imagePromises);
    
    // Footer
    ctx.fillStyle = textColor;
    ctx.font = '10px monospace';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by Flashcastr • flashcastr.app', canvas.width / 2, canvas.height - 20);
    
    // Download the image
    canvas.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `flashcastr-collection-${Date.now()}.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }
    }, 'image/png');
    
  } catch (error) {
    console.error('Error creating image grid:', error);
    // Fallback to text export
    exportAsText(flashes, title);
  }
}

function exportAsText(flashes: FavoriteFlash[], title: string) {
  const exportText = `${title}
Generated: ${new Date().toISOString()}
Total: ${flashes.length} flashes

${flashes.map(fav => 
  `#${fav.flash_id} - @${fav.player} - ${fav.city}${fav.text ? ` - "${fav.text}"` : ''}`
).join('\n')}

Exported from Flashcastr • flashcastr.app`;

  const blob = new Blob([exportText], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `flashcastr-collection-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}